Raise minimum tested compiler to 1.57
Required by the cmake crate.

    error[E0658]: use of unstable library feature 'command_access'
       --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.50/src/lib.rs:566:49
        |
    566 |         let version = Version::from_command(cmd.get_program()).unwrap_or_default();
        |                                                 ^^^^^^^^^^^